DROP TABLE IF EXISTS `TBL_PRESIDENT`;

CREATE TABLE IF NOT EXISTS `TBL_PRESIDENT`(
    `PRESIDENT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(120),
    `MIDDLE_INITIAL` VARCHAR(2) NULL_TO_DEFAULT,
    `LAST_NAME` VARCHAR(128),
    `EMAIL_ADDRESS` VARCHAR(128)
);
